export const Animations = [
    "Scroll to top",
    "On scroll",
    "On page Load",
    "Page Loader"
]

export const Projects = [
    "E-commerce site",
    "Weather webapp",
    "Todo app",
    "Social media platform",
    "Blogging site",
    "News aggregator",
    "Portfolio website",
    "Educational platform",
    "Streaming service",
    "Online forum",
    "Job board",
    "Travel booking site",
    "Fitness tracker",
    "Recipe app",
    "Finance management tool",
    "Project management tool",
    "Event planner",
    "Online store builder",
    "Photo gallery",
    "Music player",
    "Virtual classroom",
    "Language learning app",
    "Health monitoring app",
    "Real estate listing site",
    "Dating app",
    "Gaming platform",
    "Crowdfunding site",
    "Digital library",
    "Survey tool",
    "Customer support portal",
    "Meme generator",
    "Online quiz maker",
    "Podcast hosting site",
    "Online auction site",
    "Car rental service",
    "Volunteer matching platform",
    "Virtual tour site",
    "Marketplace for freelancers",
    "Interior design planner",
    "Business directory",
    "Appointment scheduler",
    "Online ticket booking",
    "Fashion styling app",
    "Virtual pet care",
    "Art showcase platform",
    "Smart home control app",
    "Meditation app",
    "DIY craft sharing site",
    "Time tracking tool",
    "Resume builder"
  ];
